{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "productpage.serviceAccountName" . }}
  labels:
{{ include "productpage.labels" . | indent 4 }}
{{- end -}}
