{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "ratings.serviceAccountName" . }}
  labels:
{{ include "ratings.labels" . | indent 4 }}
{{- end -}}
