{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "details.serviceAccountName" . }}
  labels:
{{ include "details.labels" . | indent 4 }}
{{- end -}}
