apiVersion: skaffold/v1beta17
kind: Config
build:
  artifacts:
  - image: eks-workshop-bookinfo-details
    context: src/details
  - image: eks-workshop-bookinfo-productpage
    context: src/productpage
  - image: eks-workshop-bookinfo-ratings
    context: src/ratings
  tagPolicy:
    gitCommit: {}
deploy:
  helm:
    releases:
    - name: details
      chartPath: helm-charts/details
      values: 
        image: eks-workshop-bookinfo-details
      imageStrategy:
        helm: {}  
    - name: productpage
      chartPath: helm-charts/productpage
      values:
        image: eks-workshop-bookinfo-productpage
      imageStrategy:
        helm: {}  
    - name: reviews
      chartPath: helm-charts/reviews
    - name: ratings
      chartPath: helm-charts/ratings
      values:
        image: eks-workshop-bookinfo-ratings
      imageStrategy:
        helm: {}  
    flags:
      install:
        - --atomic
      upgrade:
        - --reset-values
        - --atomic