apiVersion: skaffold/v1beta2
kind: Config
build:
  artifacts:
  - image: eks-workshop-bookinfo-details
    context: src/details
  - image: eks-workshop-bookinfo-productpage
    context: src/productpage
  - image: eks-workshop-bookinfo-reviews
    context: src/reviews
  tagPolicy:
    gitCommit: {}
deploy:
  helm:
    releases:
    - name: bookinfo-details
      chartPath: helm-charts/details
      values:
        image: eks-workshop-bookinfo-details
    - name: bookinfo-productpage
      chartPath: helm-charts/productpage
      values:
        image: eks-workshop-bookinfo-productpage
    - name: bookinfo-reviews
      chartPath: helm-charts/reviews
      values:
        image: eks-workshop-bookinfo-reviews