apiVersion: v1
kind: Service
metadata:
  name: {{ include "reviews.fullname" . }}
  labels:
{{ include "reviews.labels" . | indent 4 }}
{{ include "reviews.istio.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "reviews.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app: {{ include "reviews.name" . }}
